name: Build and Push Singularity Image to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'gapit.def'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7

      - name: Build .sif
        run: |
          singularity build GAPIT_cont.sif GAPIT.def

      - name: Install ORAS CLI
        run: |
          curl -sSfL https://github.com/oras-project/oras/releases/latest/download/oras_$(uname -s)_$(uname -m).tar.gz | tar -xz -C /usr/local/bin oras

      - name: Push to GHCR with ORAS
        env:
          ORAS_AUTH_USERNAME: ${{ github.actor }}
          ORAS_AUTH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          oras login ghcr.io -u "$ORAS_AUTH_USERNAME" -p "$ORAS_AUTH_PASSWORD"
          oras push ghcr.io/${{ github.repository_owner }}/singularity_gapit:latest \
            GAPIT_cont.sif:application/vnd.oci.image.layer.v1.tar+gzip
