name: Build and Push Singularity Image to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'GAPIT.def'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y singularity-container
          sudo apt-get install -y golang-go
          export VERSION=3.8.0
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
          tar -xvzf singularity-${VERSION}.tar.gz
          cd singularity
          ./mconfig
          make -C builddir
          sudo make -C builddir install

      - name: Build .sif
        run: |
          singularity build GAPIT_cont.sif GAPIT.def

      - name: Install ORAS CLI
        run: |
          curl -sSfL https://github.com/oras-project/oras/releases/latest/download/oras_$(uname -s)_$(uname -m).tar.gz | tar -xz -C /usr/local/bin oras

      - name: Push to GHCR with ORAS
        env:
          ORAS_AUTH_USERNAME: ${{ github.actor }}
          ORAS_AUTH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          oras login ghcr.io -u "$ORAS_AUTH_USERNAME" -p "$ORAS_AUTH_PASSWORD"
          oras push ghcr.io/${{ github.repository_owner }}/singularity_gapit:latest \
            GAPIT_cont.sif:application/vnd.oci.image.layer.v1.tar+gzip
